feat: FcmToken 저장 API
ssu-projectroy/projectory-server pull request #126
Opened 2023-08-22 18:43 UTC by Jimin0304

#124

2023-08-23 08:34 UTC, siyeonSon requested changes

2023-08-23 08:34 UTC, siyeonSon commented on bbiyong-domain/src/main/java/com/capstone/member/domain/Member.java
> +    private List<FcmToken> records = new ArrayList();
변수 명으로 records 보다 fcmTokens 등이 더 적합해 보이네용

2023-08-29 05:48 UTC, Jimin0304 commented on bbiyong-domain/src/main/java/com/capstone/member/domain/Member.java
> +    private List<FcmToken> records = new ArrayList();
아이고..! 복사하는 과정에서 제가 변수명 바꾸는 걸 까먹었네요 😅
수정해서 푸시했습니다~

2023-08-31 12:28 UTC, merged

2023-09-01 10:00 UTC, siyeonSon commented
멋있다!!!!!!

![image](https://github.com/bbiyongbbiyong/bbiyong-server/assets/87802191/8dc2c34b-25f9-4dae-a4d8-8c1c9c715ff9)